combinations/urls.py
from django.contrib import admin
from django.urls import path, include
from generic.views import *
import specific


urlpatterns = [
    path('admin/', admin.site.urls),
    path('gen/', gen, name = 'gen'),
    path('gen2/', gen2, name='gen2'),
    path('specific/', include('specific.urls')),
    
]

specific/urls.py
from specific.views import *

from django.urls import path


app_name= 's'


urlpatterns =[
    path('spe/', spe, name='spe'),
    path('spe2/', spe2, name='spe2'),
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.


def gen(request):
    return render(request, 'gen.html')




def gen2(request):
    return render(request, 'gen2.html')

specific/views.py
from django.shortcuts import render

# Create your views here.


def spe(request):
    return render(request, 'spe.html')



def spe2(request):
    return render(request, 'spe2.html')

templates/gen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        COMBINATIONS OF generic and specific 
    </h1>

    <h1>
        <a href="{% url 'gen2' %}"> generic url</a>
        <a href="{% url 's:spe' %}">specific url</a>
        <a href="{% url 's:spe2' %}"> specific2</a>


    </h1>
</body>
</html>

templates/gen2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            shortage for content
        </h1>
        
        <h1>
            <a href="{% url 'gen' %}"> generic</a>
            <a href="{% url 's:spe' %}"> specific</a>
            <a href="{% url 's:spe2' %}"> specific</a>
        </h1>
    </center>
</body>
</html>

templates/spe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>

        <h1>
            specific urlnavigation
            
        </h1>

        <h1>
            <a href="{% url 'gen' %}"> generic</a>
            <a href="{% url 'gen2' %}"> generic2</a>
            <a href="{% url 's:spe2' %}"> specific</a>

        </h1>

    </center>
</body>
</html>

templates/spe2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <cenetr>
        <h1>
            I need to be perfect in python

        </h1>

        <h1>
            <a href="{% url 'gen' %}"> generic</a>
            <a href="{% url 'gen2' %}"> generic2</a>
            <a href="{% url 's:spe' %}"> specific</a>
        </h1>

    </cenetr>
</body>
</html>